language: go

go:
- 1.14.x

notifications:
  slack: 
    rooms:
      - faustohome:R86pQ3z5xcI25gNrLIjxLpcO#latimer
    on_success: always # default: always
    on_failure: always # default: always
  email:
    recipients:
      - faustoespinal@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

env:
  - CHANGE_MINIKUBE_NONE_USER=true

before_script:
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
  - chmod 700 get_helm.sh
  - sudo ./get_helm.sh
  - helm repo add stable https://kubernetes-charts.storage.googleapis.com
  - helm repo add bitnami https://charts.bitnami.com/bitnami
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - chmod +x minikube
  - sudo mv minikube /usr/local/bin/
  - sudo minikube start --vm-driver=none --kubernetes-version=v1.17.0
  - minikube update-context
  - sleep 5
  - kubectl create ns paas
  - kubectl get ns
  - kubectl get nodes
  - helm install test-mysql --namespace paas stable/mysql
  - sleep 3
